#ifndef TEST_FUNCTIONS_H
#define TEST_FUNCTIONS_H

// This file contains a registry of all functions from attoboy.h
// Each function is registered here for coverage tracking purposes

#define REGISTER_ALL_FUNCTIONS                                                 \
  X(Exit)                                                                      \
  X(Sleep)                                                                     \
  X(GetEnv)                                                                    \
  X(SetEnv)                                                                    \
  X(Alloc)                                                                     \
  X(Realloc)                                                                   \
  X(Free)                                                                      \
  X(GetUserName)                                                               \
  X(GetUserDisplayName)                                                        \
  X(GetProcessId)                                                              \
  X(EnableLoggingToFile)                                                       \
  X(EnableLoggingToConsole)                                                    \
  X(Log)                                                                       \
  X(LogDebug)                                                                  \
  X(LogInfo)                                                                   \
  X(LogWarning)                                                                \
  X(LogError)                                                                  \
  X(String_constructor_empty)                                                  \
  X(String_constructor_cstr)                                                   \
  X(String_constructor_bool)                                                   \
  X(String_constructor_char)                                                   \
  X(String_constructor_int)                                                    \
  X(String_constructor_longlong)                                               \
  X(String_constructor_float)                                                  \
  X(String_constructor_list)                                                   \
  X(String_constructor_map)                                                    \
  X(String_constructor_set)                                                    \
  X(String_constructor_variadic)                                               \
  X(String_constructor_utf8)                                                   \
  X(String_constructor_copy)                                                   \
  X(String_FromCStr_utf8)                                                      \
  X(String_FromCStr_ansi)                                                      \
  X(String_FromCStr_cp1252)                                                    \
  X(String_destructor)                                                         \
  X(String_operator_assign)                                                    \
  X(String_length)                                                             \
  X(String_isEmpty)                                                            \
  X(String_c_str)                                                              \
  X(String_c_str_allocated_utf8)                                               \
  X(String_c_str_allocated_ansi)                                               \
  X(String_c_str_allocated_utf16)                                              \
  X(String_c_str_allocated_cp1252)                                             \
  X(String_c_str_allocated_cp1252_alias)                                       \
  X(String_at)                                                                 \
  X(String_substring)                                                          \
  X(String_duplicate)                                                          \
  X(String_contains)                                                           \
  X(String_startsWith)                                                         \
  X(String_endsWith)                                                           \
  X(String_count)                                                              \
  X(String_isNumber)                                                           \
  X(String_toInteger)                                                          \
  X(String_toFloat)                                                            \
  X(String_toBool)                                                             \
  X(String_append)                                                             \
  X(String_prepend)                                                            \
  X(String_insert)                                                             \
  X(String_remove)                                                             \
  X(String_replace)                                                            \
  X(String_trim)                                                               \
  X(String_upper)                                                              \
  X(String_lower)                                                              \
  X(String_reverse)                                                            \
  X(String_repeat)                                                             \
  X(String_equals)                                                             \
  X(String_compare)                                                            \
  X(String_operator_eq)                                                        \
  X(String_operator_ne)                                                        \
  X(String_operator_plus)                                                      \
  X(String_hash)                                                               \
  X(String_getPositionOf)                                                      \
  X(String_lines)                                                              \
  X(String_join)                                                               \
  X(String_split_separator)                                                    \
  X(String_split)                                                              \
  X(String_format_list)                                                        \
  X(String_format_map)                                                         \
  X(List_constructor_empty)                                                    \
  X(List_constructor_capacity)                                                 \
  X(List_constructor_variadic)                                                 \
  X(List_constructor_copy)                                                     \
  X(List_constructor_from_set)                                                 \
  X(List_destructor)                                                           \
  X(List_operator_assign)                                                      \
  X(List_length)                                                               \
  X(List_isEmpty)                                                              \
  X(List_append)                                                               \
  X(List_prepend)                                                              \
  X(List_insert)                                                               \
  X(List_pop)                                                                  \
  X(List_at)                                                                   \
  X(List_operator_brackets)                                                    \
  X(List_set)                                                                  \
  X(List_remove)                                                               \
  X(List_clear)                                                                \
  X(List_find)                                                                 \
  X(List_contains)                                                             \
  X(List_reverse)                                                              \
  X(List_sort)                                                                 \
  X(List_typeAt)                                                               \
  X(List_slice)                                                                \
  X(List_concat_list)                                                          \
  X(List_concat_set)                                                           \
  X(List_duplicate)                                                            \
  X(List_compare)                                                              \
  X(List_operator_eq)                                                          \
  X(List_operator_ne)                                                          \
  X(List_operator_plus)                                                        \
  X(List_toCSVString)                                                          \
  X(List_FromCSVString)                                                        \
  X(List_toJSONString)                                                         \
  X(List_FromJSONString)                                                       \
  X(Map_constructor_empty)                                                     \
  X(Map_constructor_capacity)                                                  \
  X(Map_constructor_variadic)                                                  \
  X(Map_constructor_copy)                                                      \
  X(Map_destructor)                                                            \
  X(Map_operator_assign)                                                       \
  X(Map_length)                                                                \
  X(Map_isEmpty)                                                               \
  X(Map_get)                                                                   \
  X(Map_operator_brackets)                                                     \
  X(Map_put)                                                                   \
  X(Map_remove)                                                                \
  X(Map_clear)                                                                 \
  X(Map_findValue)                                                             \
  X(Map_hasKey)                                                                \
  X(Map_typeAt)                                                                \
  X(Map_merge)                                                                 \
  X(Map_duplicate)                                                             \
  X(Map_keys)                                                                  \
  X(Map_values)                                                                \
  X(Map_compare)                                                               \
  X(Map_operator_eq)                                                           \
  X(Map_operator_ne)                                                           \
  X(Map_toJSONString)                                                          \
  X(Map_FromJSONString)                                                        \
  X(Set_constructor_empty)                                                     \
  X(Set_constructor_capacity)                                                  \
  X(Set_constructor_variadic)                                                  \
  X(Set_constructor_copy)                                                      \
  X(Set_constructor_from_list)                                                 \
  X(Set_destructor)                                                            \
  X(Set_operator_assign)                                                       \
  X(Set_length)                                                                \
  X(Set_isEmpty)                                                               \
  X(Set_put)                                                                   \
  X(Set_contains)                                                              \
  X(Set_remove)                                                                \
  X(Set_clear)                                                                 \
  X(Set_setUnion)                                                              \
  X(Set_intersect)                                                             \
  X(Set_subtract)                                                              \
  X(Set_duplicate)                                                             \
  X(Set_toList)                                                                \
  X(Set_compare)                                                               \
  X(Set_operator_eq)                                                           \
  X(Set_operator_ne)                                                           \
  X(Set_operator_plus)                                                         \
  X(Set_toJSONString)                                                          \
  X(Set_FromJSONString)                                                        \
  X(DateTime_constructor_empty)                                                \
  X(DateTime_constructor_timestamp)                                            \
  X(DateTime_constructor_components)                                           \
  X(DateTime_constructor_copy)                                                 \
  X(DateTime_destructor)                                                       \
  X(DateTime_operator_assign)                                                  \
  X(DateTime_add)                                                              \
  X(DateTime_diff)                                                             \
  X(DateTime_compare)                                                          \
  X(DateTime_operator_eq)                                                      \
  X(DateTime_operator_ne)                                                      \
  X(DateTime_operator_lt)                                                      \
  X(DateTime_operator_le)                                                      \
  X(DateTime_operator_gt)                                                      \
  X(DateTime_operator_ge)                                                      \
  X(DateTime_timestamp)                                                        \
  X(DateTime_toString)                                                         \
  X(DateTime_toStringCustom)                                                   \
  X(Buffer_constructor_empty)                                                  \
  X(Buffer_constructor_capacity)                                               \
  X(Buffer_constructor_data)                                                   \
  X(Buffer_constructor_copy)                                                   \
  X(Buffer_destructor)                                                         \
  X(Buffer_operator_assign)                                                    \
  X(Buffer_length)                                                             \
  X(Buffer_capacity)                                                           \
  X(Buffer_isEmpty)                                                            \
  X(Buffer_data)                                                               \
  X(Buffer_c_ptr)                                                              \
  X(Buffer_at)                                                                 \
  X(Buffer_operator_brackets)                                                  \
  X(Buffer_set)                                                                \
  X(Buffer_append_byte)                                                        \
  X(Buffer_append_buffer)                                                      \
  X(Buffer_append_data)                                                        \
  X(Buffer_prepend_byte)                                                       \
  X(Buffer_prepend_buffer)                                                     \
  X(Buffer_prepend_data)                                                       \
  X(Buffer_insert_byte)                                                        \
  X(Buffer_insert_buffer)                                                      \
  X(Buffer_insert_data)                                                        \
  X(Buffer_remove)                                                             \
  X(Buffer_clear)                                                              \
  X(Buffer_slice)                                                              \
  X(Buffer_duplicate)                                                          \
  X(Buffer_compare)                                                            \
  X(Buffer_operator_eq)                                                        \
  X(Buffer_operator_ne)                                                        \
  X(Buffer_compact)                                                            \
  X(Buffer_trim)                                                               \
  X(Buffer_compress)                                                           \
  X(Buffer_decompress)                                                         \
  X(Buffer_crypt_simple)                                                       \
  X(Buffer_crypt_key)                                                          \
  X(Buffer_crypt_key_iv)                                                       \
  X(Buffer_crypt_buffer_iv)                                                    \
  X(Buffer_toBase64)                                                           \
  X(Buffer_fromBase64)                                                         \
  X(Buffer_toString)                                                           \
  X(Buffer_toString_utf8)                                                      \
  X(Buffer_toString_ansi)                                                      \
  X(Buffer_append)                                                             \
  X(Arguments_constructor)                                                     \
  X(Arguments_destructor)                                                      \
  X(Arguments_operator_assign)                                                 \
  X(Arguments_count)                                                           \
  X(Arguments_at)                                                              \
  X(Arguments_operator_brackets)                                               \
  X(Arguments_has)                                                             \
  X(Arguments_get)                                                             \
  X(Arguments_getAllArguments)                                                 \
  X(Thread_constructor_empty)                                                  \
  X(Thread_constructor_function)                                               \
  X(Thread_destructor)                                                         \
  X(Thread_operator_assign)                                                    \
  X(Thread_start)                                                              \
  X(Thread_join)                                                               \
  X(Thread_detach)                                                             \
  X(Thread_isRunning)                                                          \
  X(Mutex_constructor)                                                         \
  X(Mutex_destructor)                                                          \
  X(Mutex_lock)                                                                \
  X(Mutex_unlock)                                                              \
  X(Mutex_tryLock)                                                             \
  X(Path_constructor_empty)                                                    \
  X(Path_constructor_string)                                                   \
  X(Path_constructor_copy)                                                     \
  X(Path_destructor)                                                           \
  X(Path_operator_assign)                                                      \
  X(Path_toString)                                                             \
  X(Path_isEmpty)                                                              \
  X(Path_exists)                                                               \
  X(Path_isFile)                                                               \
  X(Path_isDirectory)                                                          \
  X(Path_size)                                                                 \
  X(Path_parent)                                                               \
  X(Path_filename)                                                             \
  X(Path_extension)                                                            \
  X(Path_stem)                                                                 \
  X(Path_join)                                                                 \
  X(Path_operator_slash)                                                       \
  X(Path_absolute)                                                             \
  X(Path_relative)                                                             \
  X(Path_compare)                                                              \
  X(Path_operator_eq)                                                          \
  X(Path_operator_ne)                                                          \
  X(Path_createFile)                                                           \
  X(Path_createDirectory)                                                      \
  X(Path_remove)                                                               \
  X(Path_copy)                                                                 \
  X(Path_move)                                                                 \
  X(Path_list)                                                                 \
  X(Path_listFiles)                                                            \
  X(Path_listDirectories)                                                      \
  X(Path_current)                                                              \
  X(Path_setCurrent)                                                           \
  X(Path_temp)                                                                 \
  X(Path_home)                                                                 \
  X(Path_executable)                                                           \
  X(Path_normalize)                                                            \
  X(Path_isNamedPipe)                                                          \
  X(Path_isSymbolicLink)                                                       \
  X(Path_isOther)                                                              \
  X(Path_getCreatedOn)                                                         \
  X(Path_getModifiedOn)                                                        \
  X(Path_getAccessedOn)                                                        \
  X(Path_isReadOnly)                                                           \
  X(Path_setReadOnly)                                                          \
  X(Path_isHidden)                                                             \
  X(Path_setHidden)                                                            \
  X(Path_removeDirectory)                                                      \
  X(Path_getSymbolicLinkTarget)                                                \
  X(Path_setSymbolicLinkTarget)                                                \
  X(Path_equals)                                                               \
  X(Path_isWithin)                                                             \
  X(Path_hasExtension)                                                         \
  X(Path_readToString)                                                         \
  X(Path_readToBuffer)                                                         \
  X(Path_writeFromBuffer)                                                      \
  X(Path_writeFromString)                                                      \
  X(Path_appendFromString)                                                     \
  X(Path_appendFromBuffer)                                                     \
  X(Path_ListVolumes)                                                          \
  X(Path_CreateTemporaryFile)                                                  \
  X(Path_CreateTemporaryDirectory)                                             \
  X(Path_GetDocumentsDirectory)                                                \
  X(Path_GetRoamingAppDirectory)                                               \
  X(Path_GetLocalAppDirectory)                                                 \
  X(Path_GetCurrentDirectory)                                                  \
  X(Path_GetCurrentExecutable)                                                 \
  X(File_constructor_empty)                                                    \
  X(File_constructor_path_mode)                                                \
  X(File_constructor_path_mode_binary)                                         \
  X(File_constructor_socket)                                                   \
  X(File_destructor)                                                           \
  X(File_operator_assign)                                                      \
  X(File_isOpen)                                                               \
  X(File_close)                                                                \
  X(File_read_all)                                                             \
  X(File_read_bytes)                                                           \
  X(File_read_line)                                                            \
  X(File_write_string)                                                         \
  X(File_write_buffer)                                                         \
  X(File_write_data)                                                           \
  X(File_writeLine)                                                            \
  X(File_flush)                                                                \
  X(File_seek)                                                                 \
  X(File_tell)                                                                 \
  X(File_size)                                                                 \
  X(File_atEnd)                                                                \
  X(File_readAll)                                                              \
  X(File_writeAll)                                                             \
  X(File_bind)                                                                 \
  X(File_listen)                                                               \
  X(File_accept)                                                               \
  X(File_connect)                                                              \
  X(File_send_string)                                                          \
  X(File_send_buffer)                                                          \
  X(File_receive)                                                              \
  X(Subprocess_constructor)                                                    \
  X(Subprocess_destructor)                                                     \
  X(Subprocess_operator_assign)                                                \
  X(Subprocess_isRunning)                                                      \
  X(Subprocess_wait)                                                           \
  X(Subprocess_kill)                                                           \
  X(Subprocess_exitCode)                                                       \
  X(Subprocess_pid)                                                            \
  X(Subprocess_stdIn)                                                          \
  X(Subprocess_stdOut)                                                         \
  X(Subprocess_stdErr)                                                         \
  X(Subprocess_start)                                                          \
  X(Subprocess_run)                                                            \
  X(Subprocess_capture)                                                        \
  X(Registry_constructor_key)                                                  \
  X(Registry_constructor_key_subkey)                                           \
  X(Registry_destructor)                                                       \
  X(Registry_operator_assign)                                                  \
  X(Registry_isOpen)                                                           \
  X(Registry_close)                                                            \
  X(Registry_hasValue)                                                         \
  X(Registry_getString)                                                        \
  X(Registry_getInt)                                                           \
  X(Registry_setString)                                                        \
  X(Registry_setInt)                                                           \
  X(Registry_deleteValue)                                                      \
  X(Registry_subKeys)                                                          \
  X(Math_Random)                                                               \
  X(Math_RandomFloat)                                                          \
  X(Math_RandomRange)                                                          \
  X(Math_RandomBool)                                                           \
  X(Math_RandomChoice)                                                         \
  X(Math_Abs)                                                                  \
  X(Math_Min)                                                                  \
  X(Math_Max)                                                                  \
  X(Math_Clamp)                                                                \
  X(Math_Sign)                                                                 \
  X(Math_IsEven)                                                               \
  X(Math_IsOdd)                                                                \
  X(Math_IsPowerOfTwo)                                                         \
  X(Math_Floor)                                                                \
  X(Math_Ceil)                                                                 \
  X(Math_Trunc)                                                                \
  X(Math_Round)                                                                \
  X(Math_Exp2)                                                                 \
  X(Math_Log2)                                                                 \
  X(Math_Ln)                                                                   \
  X(Math_Log10)                                                                \
  X(Math_Exp)                                                                  \
  X(Math_Pow)                                                                  \
  X(Math_Pow2)                                                                 \
  X(Math_Sqrt)                                                                 \
  X(Math_Sin)                                                                  \
  X(Math_Cos)                                                                  \
  X(Math_Tan)                                                                  \
  X(Math_Atan2)                                                                \
  X(Math_Atan)                                                                 \
  X(Math_Asin)                                                                 \
  X(Math_Cosh)                                                                 \
  X(Math_Mod)                                                                  \
  X(Math_Lerp)                                                                 \
  X(Math_Step)                                                                 \
  X(Math_DegToRad)                                                             \
  X(Math_RadToDeg)                                                             \
  X(Math_IsFinite)                                                             \
  X(Math_IsNaN)                                                                \
  X(Math_Add64)                                                                \
  X(Math_Sub64)                                                                \
  X(Math_Mul64)                                                                \
  X(Math_Div64)                                                                \
  X(WebResponse_constructor_copy)                                              \
  X(WebResponse_destructor)                                                    \
  X(WebResponse_operator_assign)                                               \
  X(WebResponse_succeeded)                                                     \
  X(WebResponse_getUrl)                                                        \
  X(WebResponse_getStatusCode)                                                 \
  X(WebResponse_getStatusReason)                                               \
  X(WebResponse_getResponseHeaders)                                            \
  X(WebResponse_asJson)                                                        \
  X(WebResponse_asString)                                                      \
  X(WebResponse_asBuffer)                                                      \
  X(WebRequest_constructor)                                                    \
  X(WebRequest_constructor_copy)                                               \
  X(WebRequest_destructor)                                                     \
  X(WebRequest_operator_assign)                                                \
  X(WebRequest_doGet)                                                          \
  X(WebRequest_doPost_empty)                                                   \
  X(WebRequest_doPost_map)                                                     \
  X(WebRequest_doPost_list)                                                    \
  X(WebRequest_doPost_buffer)                                                  \
  X(WebRequest_doPost_string)                                                  \
  X(WebRequest_doRequest)                                                      \
  X(WebRequest_getUrl)                                                         \
  X(WebRequest_getParams)                                                      \
  X(WebRequest_getHeaders)                                                     \
  X(WebRequest_hasCompleted)                                                   \
  X(WebRequest_Download)                                                       \
  X(AI_constructor)                                                            \
  X(AI_constructor_copy)                                                       \
  X(AI_destructor)                                                             \
  X(AI_operator_assign)                                                        \
  X(AI_setModel)                                                               \
  X(AI_setSystemPrompt)                                                        \
  X(AI_setMaxTokens)                                                           \
  X(AI_setJsonMode)                                                            \
  X(AI_getModel)                                                               \
  X(AI_getSystemPrompt)                                                        \
  X(AI_getBaseUrl)                                                             \
  X(AI_getAPIKey)                                                              \
  X(AI_getPromptTokensUsed)                                                    \
  X(AI_getResponseTokensUsed)                                                  \
  X(AI_getTotalTokensUsed)                                                     \
  X(AI_resetTokenTracking)                                                     \
  X(AI_getFinishReason)                                                        \
  X(AI_ask)                                                                    \
  X(AI_createEmbedding)                                                        \
  X(AI_createConversation)                                                     \
  X(Embedding_constructor_copy)                                                \
  X(Embedding_destructor)                                                      \
  X(Embedding_operator_assign)                                                 \
  X(Embedding_compare)                                                         \
  X(Embedding_getRawArray)                                                     \
  X(Embedding_getDimensions)                                                   \
  X(Conversation_constructor_copy)                                             \
  X(Conversation_destructor)                                                   \
  X(Conversation_operator_assign)                                              \
  X(Conversation_ask)                                                          \
  X(Conversation_getConversationList)                                          \
  X(Conversation_setConversationList)                                          \
  X(Conversation_duplicate)                                                    \
  X(Conversation_getAI)                                                        \
  X(Conversation_getPromptTokensUsed)                                          \
  X(Conversation_getResponseTokensUsed)                                        \
  X(Conversation_getTotalTokensUsed)                                           \
  X(ConsoleInput_constructor_empty)                                            \
  X(ConsoleInput_constructor_copy)                                             \
  X(ConsoleInput_destructor)                                                   \
  X(ConsoleInput_operator_assign)                                              \
  X(Console_constructor_empty)                                                 \
  X(Console_destructor)                                                        \
  X(Console_width)                                                             \
  X(Console_height)                                                            \
  X(Console_print)                                                             \
  X(Console_println)                                                           \
  X(Console_clear)                                                             \
  X(Console_printAligned)                                                      \
  X(Console_printWrapped)                                                      \
  X(Console_setCursor)                                                         \
  X(Console_showCursor)                                                        \
  X(Console_hideCursor)                                                        \
  X(Console_readKey)                                                           \
  X(Console_input)                                                             \
  X(Console_progress)                                                          \
  X(Console_progressHide)                                                      \
  X(Console_menu)                                                              \
  X(Console_onHotkey)                                                          \
  X(Console_offHotkey)                                                         \
  X(Console_Align)                                                             \
  X(Console_Wrap)

// Count of all registered functions
#define FUNCTION_COUNT 499

#endif // TEST_FUNCTIONS_H
