#ifndef TEST_FUNCTIONS_H
#define TEST_FUNCTIONS_H

// This file contains a registry of all functions from attoboy.h
// Each function is registered here for coverage tracking purposes

#define REGISTER_ALL_FUNCTIONS \
    X(Exit) \
    X(Sleep) \
    X(GetEnv) \
    X(SetEnv) \
    X(Alloc) \
    X(Realloc) \
    X(Free) \
    X(GetUserName) \
    X(GetUserDisplayName) \
    X(GetProcessId) \
    X(EnableLoggingToFile) \
    X(EnableLoggingToConsole) \
    X(Log) \
    X(LogDebug) \
    X(LogInfo) \
    X(LogWarning) \
    X(LogError) \
    X(String_constructor_empty) \
    X(String_constructor_cstr) \
    X(String_constructor_bool) \
    X(String_constructor_int) \
    X(String_constructor_longlong) \
    X(String_constructor_float) \
    X(String_constructor_list) \
    X(String_constructor_map) \
    X(String_constructor_set) \
    X(String_constructor_variadic) \
    X(String_constructor_copy) \
    X(String_destructor) \
    X(String_operator_assign) \
    X(String_length) \
    X(String_isEmpty) \
    X(String_c_str) \
    X(String_at) \
    X(String_substring) \
    X(String_duplicate) \
    X(String_contains) \
    X(String_startsWith) \
    X(String_endsWith) \
    X(String_count) \
    X(String_isNumber) \
    X(String_toInteger) \
    X(String_toFloat) \
    X(String_toBool) \
    X(String_append) \
    X(String_prepend) \
    X(String_insert) \
    X(String_remove) \
    X(String_replace) \
    X(String_trim) \
    X(String_upper) \
    X(String_lower) \
    X(String_reverse) \
    X(String_repeat) \
    X(String_equals) \
    X(String_compare) \
    X(String_operator_eq) \
    X(String_operator_ne) \
    X(String_operator_plus) \
    X(String_hash) \
    X(String_lines) \
    X(String_join) \
    X(String_split_separator) \
    X(String_split_whitespace) \
    X(String_format_list) \
    X(String_format_map) \
    X(List_constructor_empty) \
    X(List_constructor_capacity) \
    X(List_constructor_variadic) \
    X(List_constructor_copy) \
    X(List_constructor_from_set) \
    X(List_destructor) \
    X(List_operator_assign) \
    X(List_length) \
    X(List_isEmpty) \
    X(List_append) \
    X(List_prepend) \
    X(List_insert) \
    X(List_pop) \
    X(List_at) \
    X(List_operator_brackets) \
    X(List_set) \
    X(List_remove) \
    X(List_clear) \
    X(List_find) \
    X(List_contains) \
    X(List_reverse) \
    X(List_sort) \
    X(List_typeAt) \
    X(List_slice) \
    X(List_concat_list) \
    X(List_concat_set) \
    X(List_duplicate) \
    X(List_compare) \
    X(List_operator_eq) \
    X(List_operator_ne) \
    X(List_operator_plus) \
    X(Map_constructor_empty) \
    X(Map_constructor_capacity) \
    X(Map_constructor_variadic) \
    X(Map_constructor_copy) \
    X(Map_destructor) \
    X(Map_operator_assign) \
    X(Map_length) \
    X(Map_isEmpty) \
    X(Map_get) \
    X(Map_operator_brackets) \
    X(Map_put) \
    X(Map_remove) \
    X(Map_clear) \
    X(Map_findValue) \
    X(Map_hasKey) \
    X(Map_typeAt) \
    X(Map_merge) \
    X(Map_duplicate) \
    X(Map_keys) \
    X(Map_values) \
    X(Map_compare) \
    X(Map_operator_eq) \
    X(Map_operator_ne) \
    X(Set_constructor_empty) \
    X(Set_constructor_capacity) \
    X(Set_constructor_variadic) \
    X(Set_constructor_copy) \
    X(Set_constructor_from_list) \
    X(Set_destructor) \
    X(Set_operator_assign) \
    X(Set_length) \
    X(Set_isEmpty) \
    X(Set_put) \
    X(Set_contains) \
    X(Set_remove) \
    X(Set_clear) \
    X(Set_setUnion) \
    X(Set_intersect) \
    X(Set_subtract) \
    X(Set_duplicate) \
    X(Set_toList) \
    X(Set_compare) \
    X(Set_operator_eq) \
    X(Set_operator_ne) \
    X(Set_operator_plus)

// Count of all registered functions
#define FUNCTION_COUNT 142

#endif // TEST_FUNCTIONS_H
